name: Applesource
favicon: null
layout_spectrum: 0
typography_spectrum: 0.3914881
title: 'Applesource - the only source for Apple news, rumours and reviews you will ever need'
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#ffffff'
    - '#ff440d'
    - '#257701'
    - '#fe9811'
    - '#0d8bff'
  brandStrength: 0.6875
  lightness: 0.3125
  saturation: 0.375
  rhythmicContrast: 0.25
purpose: []
