name: Applesource
favicon: null
layout_spectrum: 1
typography_spectrum: 0.3914881
title: 'Applesource - the only source for Apple news, rumours and reviews you will ever need!'
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#000000'
    - '#2d363f'
    - '#797e84'
    - '#b6b9bc'
    - '#e9e9e9'
  brandStrength: 0.6465848
  lightness: 0.6075269
  saturation: 0.5790613
  rhythmicContrast: 0.3512545
purpose: []
