title: 'Applesource - the only source for Apple news, rumours and reviews you will ever need'
purpose: []
collections:
  - index:
      path: /
      number: 15
      paginate: true
      navigable: true
    permalink:
      path: '/:title/'
    feed:
      path: /rss.xml
      format: rss
      number: 10
color:
  saturation: 0.4103943
  brandStrength: 0.6875
  lightness: 0.2939068
  brandColors:
    - '#ffffff'
    - '#ff440d'
    - '#257701'
    - '#fe9811'
    - '#0d8bff'
  rhythmicContrast: 0.7401434
cta:
  bucket: null
  version: null
  domain: null
analytics:
  twitter: null
  google: null
  facebook: null
favicon: null
name: Applesource
opengraph:
  image: null
  type: null
  appId: null
typography_spectrum: 0.4306
layout_spectrum: 0
