layout_spectrum: 1
typography_spectrum: 0.3914881
color:
  saturation: 0.5790613
  brandStrength: 0.6465848
  lightness: 0.6075269
  rhythmicContrast: 0.3512545
  brandColors:
    - '#71A7FE'
    - '#399AE7'
    - '#3B407C'
    - '#547AB1'
    - '#CEAFC0'
name: Applesource
