name: Applesource
favicon: null
layout_spectrum: 0.49821
typography_spectrum: 0.4306
title: 'Applesource - the only source for Apple news, rumours and reviews you will ever need'
collections:
  - index:
      path: /
      number: 15
      paginate: true
      navigable: true
    permalink:
      path: '/:title/'
    feed:
      path: /rss.xml
      format: rss
      number: 10
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#ffffff'
    - '#ff440d'
    - '#257701'
    - '#fe9811'
    - '#0d8bff'
  brandStrength: 0.125
  lightness: 0.1875
  saturation: 0.6875
  rhythmicContrast: 0.25
purpose: []
